/****************************************************************************
**
** Metadata for ScanXprLib generated by dumpcpp v5.9.9 using
** dumpcpp.exe C:\Windows\SysWOW64\ScanXpr.dll
** from the type library C:\Windows\SysWOW64\ScanXpr.dll
**
****************************************************************************/

#define QAX_DUMPCPP_SCANXPRLIB_NOINLINES
#include "scanxprlib.h"

using namespace ScanXprLib;

struct qt_meta_stringdata_all_t {
    QByteArrayData data[143];
    char stringdata0[1893];
};
#define QT_MOC_LITERAL(idx, ofs, len, table) \
    Q_STATIC_BYTE_ARRAY_DATA_HEADER_INITIALIZER_WITH_OFFSET(len, \
    offsetof(qt_meta_stringdata_all_t, stringdata##table) + ofs \
        - idx * sizeof(QByteArrayData) \
    )
static const qt_meta_stringdata_all_t qt_meta_stringdata_all = {
    {
QT_MOC_LITERAL(0, 0, 23, 0),
QT_MOC_LITERAL(1, 24, 9, 0),
QT_MOC_LITERAL(2, 34, 0, 0),
QT_MOC_LITERAL(3, 35, 4, 0),
QT_MOC_LITERAL(4, 40, 6, 0),
QT_MOC_LITERAL(5, 47, 4, 0),
QT_MOC_LITERAL(6, 52, 4, 0),
QT_MOC_LITERAL(7, 57, 15, 0),
QT_MOC_LITERAL(8, 73, 4, 0),
QT_MOC_LITERAL(9, 78, 6, 0),
QT_MOC_LITERAL(10, 85, 4, 0),
QT_MOC_LITERAL(11, 90, 4, 0),
QT_MOC_LITERAL(12, 95, 5, 0),
QT_MOC_LITERAL(13, 101, 6, 0),
QT_MOC_LITERAL(14, 108, 10, 0),
QT_MOC_LITERAL(15, 119, 19, 0),
QT_MOC_LITERAL(16, 139, 8, 0),
QT_MOC_LITERAL(17, 148, 12, 0),
QT_MOC_LITERAL(18, 161, 8, 0),
QT_MOC_LITERAL(19, 170, 12, 0),
QT_MOC_LITERAL(20, 183, 9, 0),
QT_MOC_LITERAL(21, 193, 15, 0),
QT_MOC_LITERAL(22, 209, 5, 0),
QT_MOC_LITERAL(23, 215, 14, 0),
QT_MOC_LITERAL(24, 230, 10, 0),
QT_MOC_LITERAL(25, 241, 12, 0),
QT_MOC_LITERAL(26, 254, 9, 0),
QT_MOC_LITERAL(27, 264, 13, 0),
QT_MOC_LITERAL(28, 278, 10, 0),
QT_MOC_LITERAL(29, 289, 8, 0),
QT_MOC_LITERAL(30, 298, 5, 0),
QT_MOC_LITERAL(31, 304, 10, 0),
QT_MOC_LITERAL(32, 315, 7, 0),
QT_MOC_LITERAL(33, 323, 10, 0),
QT_MOC_LITERAL(34, 334, 7, 0),
QT_MOC_LITERAL(35, 342, 15, 0),
QT_MOC_LITERAL(36, 358, 19, 0),
QT_MOC_LITERAL(37, 378, 12, 0),
QT_MOC_LITERAL(38, 391, 14, 0),
QT_MOC_LITERAL(39, 406, 11, 0),
QT_MOC_LITERAL(40, 418, 15, 0),
QT_MOC_LITERAL(41, 434, 12, 0),
QT_MOC_LITERAL(42, 447, 15, 0),
QT_MOC_LITERAL(43, 463, 12, 0),
QT_MOC_LITERAL(44, 476, 17, 0),
QT_MOC_LITERAL(45, 494, 14, 0),
QT_MOC_LITERAL(46, 509, 16, 0),
QT_MOC_LITERAL(47, 526, 13, 0),
QT_MOC_LITERAL(48, 540, 11, 0),
QT_MOC_LITERAL(49, 552, 8, 0),
QT_MOC_LITERAL(50, 561, 14, 0),
QT_MOC_LITERAL(51, 576, 18, 0),
QT_MOC_LITERAL(52, 595, 11, 0),
QT_MOC_LITERAL(53, 607, 19, 0),
QT_MOC_LITERAL(54, 627, 16, 0),
QT_MOC_LITERAL(55, 644, 18, 0),
QT_MOC_LITERAL(56, 663, 15, 0),
QT_MOC_LITERAL(57, 679, 17, 0),
QT_MOC_LITERAL(58, 697, 14, 0),
QT_MOC_LITERAL(59, 712, 12, 0),
QT_MOC_LITERAL(60, 725, 9, 0),
QT_MOC_LITERAL(61, 735, 14, 0),
QT_MOC_LITERAL(62, 750, 4, 0),
QT_MOC_LITERAL(63, 755, 7, 0),
QT_MOC_LITERAL(64, 763, 7, 0),
QT_MOC_LITERAL(65, 771, 6, 0),
QT_MOC_LITERAL(66, 778, 13, 0),
QT_MOC_LITERAL(67, 792, 13, 0),
QT_MOC_LITERAL(68, 806, 14, 0),
QT_MOC_LITERAL(69, 821, 17, 0),
QT_MOC_LITERAL(70, 839, 13, 0),
QT_MOC_LITERAL(71, 853, 15, 0),
QT_MOC_LITERAL(72, 869, 14, 0),
QT_MOC_LITERAL(73, 884, 13, 0),
QT_MOC_LITERAL(74, 898, 16, 0),
QT_MOC_LITERAL(75, 915, 7, 0),
QT_MOC_LITERAL(76, 923, 4, 0),
QT_MOC_LITERAL(77, 928, 11, 0),
QT_MOC_LITERAL(78, 940, 13, 0),
QT_MOC_LITERAL(79, 954, 15, 0),
QT_MOC_LITERAL(80, 970, 16, 0),
QT_MOC_LITERAL(81, 987, 18, 0),
QT_MOC_LITERAL(82, 1006, 21, 0),
QT_MOC_LITERAL(83, 1028, 16, 0),
QT_MOC_LITERAL(84, 1045, 15, 0),
QT_MOC_LITERAL(85, 1061, 15, 0),
QT_MOC_LITERAL(86, 1077, 18, 0),
QT_MOC_LITERAL(87, 1096, 17, 0),
QT_MOC_LITERAL(88, 1114, 18, 0),
QT_MOC_LITERAL(89, 1133, 18, 0),
QT_MOC_LITERAL(90, 1152, 16, 0),
QT_MOC_LITERAL(91, 1169, 18, 0),
QT_MOC_LITERAL(92, 1188, 23, 0),
QT_MOC_LITERAL(93, 1212, 13, 0),
QT_MOC_LITERAL(94, 1226, 12, 0),
QT_MOC_LITERAL(95, 1239, 13, 0),
QT_MOC_LITERAL(96, 1253, 11, 0),
QT_MOC_LITERAL(97, 1265, 17, 0),
QT_MOC_LITERAL(98, 1283, 16, 0),
QT_MOC_LITERAL(99, 1300, 17, 0),
QT_MOC_LITERAL(100, 1318, 19, 0),
QT_MOC_LITERAL(101, 1338, 16, 0),
QT_MOC_LITERAL(102, 1355, 17, 0),
QT_MOC_LITERAL(103, 1373, 16, 0),
QT_MOC_LITERAL(104, 1390, 11, 0),
QT_MOC_LITERAL(105, 1402, 14, 0),
QT_MOC_LITERAL(106, 1417, 13, 0),
QT_MOC_LITERAL(107, 1431, 11, 0),
QT_MOC_LITERAL(108, 1443, 17, 0),
QT_MOC_LITERAL(109, 1461, 7, 0),
QT_MOC_LITERAL(110, 1469, 12, 0),
QT_MOC_LITERAL(111, 1482, 6, 0),
QT_MOC_LITERAL(112, 1489, 7, 0),
QT_MOC_LITERAL(113, 1497, 6, 0),
QT_MOC_LITERAL(114, 1504, 15, 0),
QT_MOC_LITERAL(115, 1520, 15, 0),
QT_MOC_LITERAL(116, 1536, 12, 0),
QT_MOC_LITERAL(117, 1549, 14, 0),
QT_MOC_LITERAL(118, 1564, 12, 0),
QT_MOC_LITERAL(119, 1577, 13, 0),
QT_MOC_LITERAL(120, 1591, 13, 0),
QT_MOC_LITERAL(121, 1605, 14, 0),
QT_MOC_LITERAL(122, 1620, 15, 0),
QT_MOC_LITERAL(123, 1636, 11, 0),
QT_MOC_LITERAL(124, 1648, 8, 0),
QT_MOC_LITERAL(125, 1657, 9, 0),
QT_MOC_LITERAL(126, 1667, 17, 0),
QT_MOC_LITERAL(127, 1685, 14, 0),
QT_MOC_LITERAL(128, 1700, 19, 0),
QT_MOC_LITERAL(129, 1720, 17, 0),
QT_MOC_LITERAL(130, 1738, 22, 0),
QT_MOC_LITERAL(131, 1761, 17, 0),
QT_MOC_LITERAL(132, 1779, 14, 0),
QT_MOC_LITERAL(133, 1794, 11, 0),
QT_MOC_LITERAL(134, 1806, 11, 0),
QT_MOC_LITERAL(135, 1818, 9, 0),
QT_MOC_LITERAL(136, 1828, 10, 0),
QT_MOC_LITERAL(137, 1839, 10, 0),
QT_MOC_LITERAL(138, 1850, 11, 0),
QT_MOC_LITERAL(139, 1862, 5, 0),
QT_MOC_LITERAL(140, 1868, 8, 0),
QT_MOC_LITERAL(141, 1877, 6, 0),
QT_MOC_LITERAL(142, 1884, 7, 0)
    },
    "ScanXprLib::IScanXpress\0exception\0\0code\0source\0disc\0help\0propertyChanged\0"
    "name\0signal\0argc\0argv\0About\0Cancel\0bImmediate\0ClearScanAheadPages\0LoadPipe\0"
    "LoadSettings\0FileName\0SaveSettings\0ScanBatch\0ScanChoiceAscii\0Index\0ScanChoiceLong\0"
    "ScanSingle\0SetCreateDib\0CreateDib\0SetCreateFile\0CreateFile\0SetDebug\0Debug\0"
    "SetEnabled\0Enabled\0SetFlipDib\0FlipDib\0SetSaveFileType\0tagenumSaveFileType\0"
    "SaveFileType\0SetScanFileDir\0ScanFileDir\0SetScanFileName\0ScanFileName\0"
    "SetScanFileRoot\0ScanFileRoot\0SetScanFileSchema\0ScanFileSchema\0SetScanMultiPage\0"
    "ScanMultiPage\0SetScanName\0ScanName\0SetScanSetting\0tagenumScanSetting\0ScanSetting\0"
    "SetScanSettingAscii\0ScanSettingAscii\0SetScanSettingLong\0ScanSettingLong\0"
    "SetUseCompression\0UseCompression\0SetUseSchema\0UseSchema\0SettingsDialog\0hWnd\0"
    "dwFlags\0IHeight\0IWidth\0ScanChoiceMax\0ScanChoiceMin\0ScanChoiceType\0tagenumChoiceType\0"
    "ScanErrorCode\0ScanErrorString\0ScanNumChoices\0ScannerLoaded\0SettingSupported\0"
    "control\0hDib\0ChoiceRange\0ChoiceListInt\0ChoiceListAscii\0tagenumConstants\0"
    "SCANTYPE_AUTOMATIC\0SCANTYPE_TRANSPARENCY\0SCANTYPE_FLATBED\0SCANTYPE_FEEDER\0"
    "SCANTYPE_DUPLEX\0SCANTYPE_BACKFRONT\0SCANTYPE_BACKONLY\0SCANSETTING_NORMAL\0"
    "SCANSETTING_BINARY\0SCANSETTING_AREA\0SCANSETTING_RETURN\0SCANSETTING_AREAPREVIEW\0"
    "SCANAHEAD_OFF\0SCANAHEAD_ON\0tagenumErrors\0SCANERR_PIX\0SCANERR_NOSCANNER\0"
    "SCANERR_BADINDEX\0SCANERR_BADLENGTH\0SCANERR_OUTOFMEMORY\0SCANERR_BADVALUE\0"
    "SCANERR_BADSCHEMA\0SCANERR_NOTAVAIL\0SCANERR_INI\0SCANERR_CANCEL\0SCANERR_NODIB\0"
    "SCANERR_SEQ\0SCANERR_NOLICENSE\0TIF_Raw\0TIF_PackBits\0TIF_G3\0TIF_G3M\0TIF_G4\0"
    "ScanXResolution\0ScanYResolution\0ScanPageSize\0ScanBrightness\0ScanContrast\0"
    "ScanXPosition\0ScanYPosition\0ScanImageWidth\0ScanImageLength\0ScanResUnit\0"
    "ScanType\0ScanAhead\0ScanAheadMaxPages\0ScanAheadPages\0ScanSamplesPerPixel\0"
    "ScanBitsPerSample\0ScanXprLib::ScanXpress\0Event Interface 1\0IScanXprEvents\0"
    "Interface 0\0IScanXpress\0AfterScan\0PageNumber\0BeforeScan\0FeederEmpty\0bool&\0"
    "StopScan\0Status\0Percent\0"
};
#undef QT_MOC_LITERAL

static const uint qt_meta_data_ScanXprLib__IScanXpress[] = {

 // content:
    7, // revision
    0,  // classname
    0, 0, // classinfo
    35, 14, // methods
    29, 290, // properties
    5, 377, // enums/sets
    0, 0, // constructors
    0, // flags
    3, // signal count

// signal: name, argc, parameters, tag, flags
    1, 4, 189, 2, 5,
    7, 1, 198, 2, 5,
    9, 3, 201, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 208, 2, 9,
    13, 0, 209, 2, 11,
    13, 1, 210, 2, 9,
    15, 0, 213, 2, 9,
    16, 0, 214, 2, 9,
    17, 1, 215, 2, 9,
    19, 1, 218, 2, 9,
    20, 0, 221, 2, 9,
    21, 1, 222, 2, 9,
    23, 1, 225, 2, 9,
    24, 0, 228, 2, 9,
    25, 1, 229, 2, 9,
    27, 1, 232, 2, 9,
    29, 1, 235, 2, 9,
    31, 1, 238, 2, 9,
    33, 1, 241, 2, 9,
    35, 1, 244, 2, 9,
    38, 1, 247, 2, 9,
    40, 1, 250, 2, 9,
    42, 1, 253, 2, 9,
    44, 1, 256, 2, 9,
    46, 1, 259, 2, 9,
    48, 0, 262, 2, 9,
    48, 1, 263, 2, 9,
    50, 1, 266, 2, 9,
    53, 1, 269, 2, 9,
    55, 1, 272, 2, 9,
    57, 1, 275, 2, 9,
    59, 1, 278, 2, 9,
    61, 0, 281, 2, 11,
    61, 1, 282, 2, 11,
    61, 2, 285, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 14,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void,
    QMetaType::QString, QMetaType::Int, 22,
    QMetaType::Int, QMetaType::Int, 22,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 26,
    QMetaType::Void, QMetaType::Bool, 28,
    QMetaType::Void, QMetaType::Bool, 30,
    QMetaType::Void, QMetaType::Bool, 32,
    QMetaType::Void, QMetaType::Bool, 34,
    QMetaType::Void, 0x80000000 | 36, 37,
    QMetaType::Void, QMetaType::QString, 39,
    QMetaType::Void, QMetaType::QString, 41,
    QMetaType::Void, QMetaType::QString, 43,
    QMetaType::Void, QMetaType::QString, 45,
    QMetaType::Void, QMetaType::Bool, 47,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 49,
    QMetaType::Void, 0x80000000 | 51, 52,
    QMetaType::Void, QMetaType::QString, 54,
    QMetaType::Void, QMetaType::Int, 56,
    QMetaType::Void, QMetaType::Bool, 58,
    QMetaType::Void, QMetaType::Bool, 60,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QVariant, 62,
    QMetaType::Void, QMetaType::QVariant, QMetaType::QVariant, 62, 63,

 // properties: name, type, flags
    26, QMetaType::Bool, 0x01015003, 		 // bool CreateDib
    28, QMetaType::Bool, 0x01015003, 		 // bool CreateFile
    30, QMetaType::Bool, 0x01014003, 		 // bool Debug
    32, QMetaType::Bool, 0x01015003, 		 // bool Enabled
    34, QMetaType::Bool, 0x01015003, 		 // bool FlipDib
    64, QMetaType::Int, 0x02004001, 		 // int IHeight
    65, QMetaType::Int, 0x02004001, 		 // int IWidth
    37, 0x80000000 | 36, 0x0201500b, 		 // tagenumSaveFileType SaveFileType
    66, QMetaType::Int, 0x02004001, 		 // int ScanChoiceMax
    67, QMetaType::Int, 0x02004001, 		 // int ScanChoiceMin
    68, 0x80000000 | 69, 0x02004009, 		 // tagenumChoiceType ScanChoiceType
    70, QMetaType::Int, 0x02004001, 		 // int ScanErrorCode
    71, QMetaType::QString, 0x0a004001, 		 // QString ScanErrorString
    39, QMetaType::QString, 0x0a015003, 		 // QString ScanFileDir
    41, QMetaType::QString, 0x0a015003, 		 // QString ScanFileName
    43, QMetaType::QString, 0x0a015003, 		 // QString ScanFileRoot
    45, QMetaType::QString, 0x0a015003, 		 // QString ScanFileSchema
    47, QMetaType::Bool, 0x01015003, 		 // bool ScanMultiPage
    49, QMetaType::QString, 0x0a014003, 		 // QString ScanName
    72, QMetaType::Int, 0x02004001, 		 // int ScanNumChoices
    52, 0x80000000 | 51, 0x0201400b, 		 // tagenumScanSetting ScanSetting
    54, QMetaType::QString, 0x0a014003, 		 // QString ScanSettingAscii
    56, QMetaType::Int, 0x02014003, 		 // int ScanSettingLong
    73, QMetaType::Bool, 0x01004001, 		 // bool ScannerLoaded
    74, QMetaType::Bool, 0x01005001, 		 // bool SettingSupported
    58, QMetaType::Bool, 0x01015003, 		 // bool UseCompression
    60, QMetaType::Bool, 0x01015003, 		 // bool UseSchema
    75, QMetaType::QString, 0x0a055003, 		 // QString control
    76, QMetaType::Int, 0x02004001, 		 // int hDib

 // enums: name, flags, count, data
    69, 0x0, 3, 397, 
    80, 0x0, 14, 403, 
    95, 0x0, 13, 431, 
    36, 0x0, 5, 457, 
    51, 0x0, 16, 467, 

 // enum data: key, value
    77, uint(ScanXprLib::ChoiceRange),
    78, uint(ScanXprLib::ChoiceListInt),
    79, uint(ScanXprLib::ChoiceListAscii),
    81, uint(ScanXprLib::SCANTYPE_AUTOMATIC),
    82, uint(ScanXprLib::SCANTYPE_TRANSPARENCY),
    83, uint(ScanXprLib::SCANTYPE_FLATBED),
    84, uint(ScanXprLib::SCANTYPE_FEEDER),
    85, uint(ScanXprLib::SCANTYPE_DUPLEX),
    86, uint(ScanXprLib::SCANTYPE_BACKFRONT),
    87, uint(ScanXprLib::SCANTYPE_BACKONLY),
    88, uint(ScanXprLib::SCANSETTING_NORMAL),
    89, uint(ScanXprLib::SCANSETTING_BINARY),
    90, uint(ScanXprLib::SCANSETTING_AREA),
    91, uint(ScanXprLib::SCANSETTING_RETURN),
    92, uint(ScanXprLib::SCANSETTING_AREAPREVIEW),
    93, uint(ScanXprLib::SCANAHEAD_OFF),
    94, uint(ScanXprLib::SCANAHEAD_ON),
    96, uint(ScanXprLib::SCANERR_PIX),
    97, uint(ScanXprLib::SCANERR_NOSCANNER),
    98, uint(ScanXprLib::SCANERR_BADINDEX),
    99, uint(ScanXprLib::SCANERR_BADLENGTH),
    100, uint(ScanXprLib::SCANERR_OUTOFMEMORY),
    101, uint(ScanXprLib::SCANERR_BADVALUE),
    102, uint(ScanXprLib::SCANERR_BADSCHEMA),
    103, uint(ScanXprLib::SCANERR_NOTAVAIL),
    104, uint(ScanXprLib::SCANERR_INI),
    105, uint(ScanXprLib::SCANERR_CANCEL),
    106, uint(ScanXprLib::SCANERR_NODIB),
    107, uint(ScanXprLib::SCANERR_SEQ),
    108, uint(ScanXprLib::SCANERR_NOLICENSE),
    109, uint(ScanXprLib::TIF_Raw),
    110, uint(ScanXprLib::TIF_PackBits),
    111, uint(ScanXprLib::TIF_G3),
    112, uint(ScanXprLib::TIF_G3M),
    113, uint(ScanXprLib::TIF_G4),
    114, uint(ScanXprLib::ScanXResolution),
    115, uint(ScanXprLib::ScanYResolution),
    116, uint(ScanXprLib::ScanPageSize),
    117, uint(ScanXprLib::ScanBrightness),
    118, uint(ScanXprLib::ScanContrast),
    119, uint(ScanXprLib::ScanXPosition),
    120, uint(ScanXprLib::ScanYPosition),
    121, uint(ScanXprLib::ScanImageWidth),
    122, uint(ScanXprLib::ScanImageLength),
    123, uint(ScanXprLib::ScanResUnit),
    124, uint(ScanXprLib::ScanType),
    125, uint(ScanXprLib::ScanAhead),
    126, uint(ScanXprLib::ScanAheadMaxPages),
    127, uint(ScanXprLib::ScanAheadPages),
    128, uint(ScanXprLib::ScanSamplesPerPixel),
    129, uint(ScanXprLib::ScanBitsPerSample),
    0 // eod
};

const QMetaObject IScanXpress::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ScanXprLib__IScanXpress, 0, 0, 0 }
};

void *IScanXpress::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ScanXprLib::IScanXpress"))
        return static_cast<void*>(const_cast<IScanXpress*>(this));
    return QAxObject::qt_metacast(_clname);
}
static const uint qt_meta_data_ScanXprLib__ScanXpress[] = {

 // content:
    7, // revision
    130,  // classname
    2, 14, // classinfo
    39, 18, // methods
    28, 328, // properties
    5, 412, // enums/sets
    0, 0, // constructors
    0, // flags
    7, // signal count

 // classinfo: key, value
    131, 132, 
    133, 134, 

// signal: name, argc, parameters, tag, flags
    135, 1, 213, 2, 5,
    137, 1, 216, 2, 5,
    138, 2, 219, 2, 5,
    141, 1, 224, 2, 5,
    1, 4, 227, 2, 5,
    7, 1, 236, 2, 5,
    9, 3, 239, 2, 5,

// slot: name, argc, parameters, tag, flags
    12, 0, 246, 2, 9,
    13, 0, 247, 2, 11,
    13, 1, 248, 2, 9,
    15, 0, 251, 2, 9,
    16, 0, 252, 2, 9,
    17, 1, 253, 2, 9,
    19, 1, 256, 2, 9,
    20, 0, 259, 2, 9,
    21, 1, 260, 2, 9,
    23, 1, 263, 2, 9,
    24, 0, 266, 2, 9,
    25, 1, 267, 2, 9,
    27, 1, 270, 2, 9,
    29, 1, 273, 2, 9,
    31, 1, 276, 2, 9,
    33, 1, 279, 2, 9,
    35, 1, 282, 2, 9,
    38, 1, 285, 2, 9,
    40, 1, 288, 2, 9,
    42, 1, 291, 2, 9,
    44, 1, 294, 2, 9,
    46, 1, 297, 2, 9,
    48, 0, 300, 2, 9,
    48, 1, 301, 2, 9,
    50, 1, 304, 2, 9,
    53, 1, 307, 2, 9,
    55, 1, 310, 2, 9,
    57, 1, 313, 2, 9,
    59, 1, 316, 2, 9,
    61, 0, 319, 2, 11,
    61, 1, 320, 2, 11,
    61, 2, 323, 2, 9,

// signal: parameters
    QMetaType::Void, QMetaType::Int, 136,
    QMetaType::Void, QMetaType::Int, 136,
    QMetaType::Void, QMetaType::Int, 0x80000000 | 139, 136, 140,
    QMetaType::Void, QMetaType::Int, 142,
    QMetaType::Void, QMetaType::Int, QMetaType::QString, QMetaType::QString, QMetaType::QString, 3, 4, 5, 6,
    QMetaType::Void, QMetaType::QString, 8,
    QMetaType::Void, QMetaType::QString, QMetaType::Int, QMetaType::VoidStar, 8, 10, 11,

// slot: parameters
    QMetaType::Void,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 14,
    QMetaType::Int,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void, QMetaType::QString, 18,
    QMetaType::Void,
    QMetaType::QString, QMetaType::Int, 22,
    QMetaType::Int, QMetaType::Int, 22,
    QMetaType::Void,
    QMetaType::Void, QMetaType::Bool, 26,
    QMetaType::Void, QMetaType::Bool, 28,
    QMetaType::Void, QMetaType::Bool, 30,
    QMetaType::Void, QMetaType::Bool, 32,
    QMetaType::Void, QMetaType::Bool, 34,
    QMetaType::Void, 0x80000000 | 36, 37,
    QMetaType::Void, QMetaType::QString, 39,
    QMetaType::Void, QMetaType::QString, 41,
    QMetaType::Void, QMetaType::QString, 43,
    QMetaType::Void, QMetaType::QString, 45,
    QMetaType::Void, QMetaType::Bool, 47,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QString, 49,
    QMetaType::Void, 0x80000000 | 51, 52,
    QMetaType::Void, QMetaType::QString, 54,
    QMetaType::Void, QMetaType::Int, 56,
    QMetaType::Void, QMetaType::Bool, 58,
    QMetaType::Void, QMetaType::Bool, 60,
    QMetaType::Void,
    QMetaType::Void, QMetaType::QVariant, 62,
    QMetaType::Void, QMetaType::QVariant, QMetaType::QVariant, 62, 63,

 // properties: name, type, flags
    26, QMetaType::Bool, 0x01015003, 		 // bool CreateDib
    28, QMetaType::Bool, 0x01015003, 		 // bool CreateFile
    30, QMetaType::Bool, 0x01014003, 		 // bool Debug
    32, QMetaType::Bool, 0x01015003, 		 // bool Enabled
    34, QMetaType::Bool, 0x01015003, 		 // bool FlipDib
    64, QMetaType::Int, 0x02004001, 		 // int IHeight
    65, QMetaType::Int, 0x02004001, 		 // int IWidth
    37, 0x80000000 | 36, 0x0201500b, 		 // tagenumSaveFileType SaveFileType
    66, QMetaType::Int, 0x02004001, 		 // int ScanChoiceMax
    67, QMetaType::Int, 0x02004001, 		 // int ScanChoiceMin
    68, 0x80000000 | 69, 0x02004009, 		 // tagenumChoiceType ScanChoiceType
    70, QMetaType::Int, 0x02004001, 		 // int ScanErrorCode
    71, QMetaType::QString, 0x0a004001, 		 // QString ScanErrorString
    39, QMetaType::QString, 0x0a015003, 		 // QString ScanFileDir
    41, QMetaType::QString, 0x0a015003, 		 // QString ScanFileName
    43, QMetaType::QString, 0x0a015003, 		 // QString ScanFileRoot
    45, QMetaType::QString, 0x0a015003, 		 // QString ScanFileSchema
    47, QMetaType::Bool, 0x01015003, 		 // bool ScanMultiPage
    49, QMetaType::QString, 0x0a014003, 		 // QString ScanName
    72, QMetaType::Int, 0x02004001, 		 // int ScanNumChoices
    52, 0x80000000 | 51, 0x0201400b, 		 // tagenumScanSetting ScanSetting
    54, QMetaType::QString, 0x0a014003, 		 // QString ScanSettingAscii
    56, QMetaType::Int, 0x02014003, 		 // int ScanSettingLong
    73, QMetaType::Bool, 0x01004001, 		 // bool ScannerLoaded
    74, QMetaType::Bool, 0x01005001, 		 // bool SettingSupported
    58, QMetaType::Bool, 0x01015003, 		 // bool UseCompression
    60, QMetaType::Bool, 0x01015003, 		 // bool UseSchema
    76, QMetaType::Int, 0x02004001, 		 // int hDib

 // enums: name, flags, count, data
    69, 0x0, 3, 432, 
    80, 0x0, 14, 438, 
    95, 0x0, 13, 466, 
    36, 0x0, 5, 492, 
    51, 0x0, 16, 502, 

 // enum data: key, value
    77, uint(ScanXprLib::ChoiceRange),
    78, uint(ScanXprLib::ChoiceListInt),
    79, uint(ScanXprLib::ChoiceListAscii),
    81, uint(ScanXprLib::SCANTYPE_AUTOMATIC),
    82, uint(ScanXprLib::SCANTYPE_TRANSPARENCY),
    83, uint(ScanXprLib::SCANTYPE_FLATBED),
    84, uint(ScanXprLib::SCANTYPE_FEEDER),
    85, uint(ScanXprLib::SCANTYPE_DUPLEX),
    86, uint(ScanXprLib::SCANTYPE_BACKFRONT),
    87, uint(ScanXprLib::SCANTYPE_BACKONLY),
    88, uint(ScanXprLib::SCANSETTING_NORMAL),
    89, uint(ScanXprLib::SCANSETTING_BINARY),
    90, uint(ScanXprLib::SCANSETTING_AREA),
    91, uint(ScanXprLib::SCANSETTING_RETURN),
    92, uint(ScanXprLib::SCANSETTING_AREAPREVIEW),
    93, uint(ScanXprLib::SCANAHEAD_OFF),
    94, uint(ScanXprLib::SCANAHEAD_ON),
    96, uint(ScanXprLib::SCANERR_PIX),
    97, uint(ScanXprLib::SCANERR_NOSCANNER),
    98, uint(ScanXprLib::SCANERR_BADINDEX),
    99, uint(ScanXprLib::SCANERR_BADLENGTH),
    100, uint(ScanXprLib::SCANERR_OUTOFMEMORY),
    101, uint(ScanXprLib::SCANERR_BADVALUE),
    102, uint(ScanXprLib::SCANERR_BADSCHEMA),
    103, uint(ScanXprLib::SCANERR_NOTAVAIL),
    104, uint(ScanXprLib::SCANERR_INI),
    105, uint(ScanXprLib::SCANERR_CANCEL),
    106, uint(ScanXprLib::SCANERR_NODIB),
    107, uint(ScanXprLib::SCANERR_SEQ),
    108, uint(ScanXprLib::SCANERR_NOLICENSE),
    109, uint(ScanXprLib::TIF_Raw),
    110, uint(ScanXprLib::TIF_PackBits),
    111, uint(ScanXprLib::TIF_G3),
    112, uint(ScanXprLib::TIF_G3M),
    113, uint(ScanXprLib::TIF_G4),
    114, uint(ScanXprLib::ScanXResolution),
    115, uint(ScanXprLib::ScanYResolution),
    116, uint(ScanXprLib::ScanPageSize),
    117, uint(ScanXprLib::ScanBrightness),
    118, uint(ScanXprLib::ScanContrast),
    119, uint(ScanXprLib::ScanXPosition),
    120, uint(ScanXprLib::ScanYPosition),
    121, uint(ScanXprLib::ScanImageWidth),
    122, uint(ScanXprLib::ScanImageLength),
    123, uint(ScanXprLib::ScanResUnit),
    124, uint(ScanXprLib::ScanType),
    125, uint(ScanXprLib::ScanAhead),
    126, uint(ScanXprLib::ScanAheadMaxPages),
    127, uint(ScanXprLib::ScanAheadPages),
    128, uint(ScanXprLib::ScanSamplesPerPixel),
    129, uint(ScanXprLib::ScanBitsPerSample),
    0 // eod
};

const QMetaObject ScanXpress::staticMetaObject = {
{ &QWidget::staticMetaObject,
qt_meta_stringdata_all.data,
qt_meta_data_ScanXprLib__ScanXpress, 0, 0, 0 }
};

void *ScanXpress::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, "ScanXprLib::ScanXpress"))
        return static_cast<void*>(const_cast<ScanXpress*>(this));
    return QAxWidget::qt_metacast(_clname);
}

