/****************************************************************************
**
** Namespace ScanXprLib generated by dumpcpp v5.9.9 using
** dumpcpp.exe C:\Windows\SysWOW64\ScanXpr.dll
** from the type library C:\Windows\SysWOW64\ScanXpr.dll
**
****************************************************************************/

#ifndef QAX_DUMPCPP_SCANXPRLIB_H
#define QAX_DUMPCPP_SCANXPRLIB_H

// Define this symbol to __declspec(dllexport) or __declspec(dllimport)
#ifndef SCANXPRLIB_EXPORT
#define SCANXPRLIB_EXPORT
#endif
#include <qaxobject.h>
#include <qaxwidget.h>
#include <qdatetime.h>
#include <qpixmap.h>
#include <iostream>
using namespace std;

struct IDispatch;


// Referenced namespace

namespace ScanXprLib {

    enum tagenumChoiceType {
        ChoiceRange             = 0,
        ChoiceListInt           = 1,
        ChoiceListAscii         = 2
    };

    enum tagenumConstants {
        SCANTYPE_AUTOMATIC      = 0,
        SCANTYPE_TRANSPARENCY   = 1,
        SCANTYPE_FLATBED        = 2,
        SCANTYPE_FEEDER         = 3,
        SCANTYPE_DUPLEX         = 4,
        SCANTYPE_BACKFRONT      = 5,
        SCANTYPE_BACKONLY       = 6,
        SCANSETTING_NORMAL      = 0,
        SCANSETTING_BINARY      = 1,
        SCANSETTING_AREA        = 2,
        SCANSETTING_RETURN      = 4,
        SCANSETTING_AREAPREVIEW = 8,
        SCANAHEAD_OFF           = 0,
        SCANAHEAD_ON            = 1
    };

    enum tagenumErrors {
        SCANERR_PIX             = 1000,
        SCANERR_NOSCANNER       = 1001,
        SCANERR_BADINDEX        = 1002,
        SCANERR_BADLENGTH       = 1003,
        SCANERR_OUTOFMEMORY     = 1004,
        SCANERR_BADVALUE        = 1005,
        SCANERR_BADSCHEMA       = 1006,
        SCANERR_NOTAVAIL        = 1007,
        SCANERR_INI             = 1008,
        SCANERR_CANCEL          = 1009,
        SCANERR_NODIB           = 1010,
        SCANERR_SEQ             = 1014,
        SCANERR_NOLICENSE       = 2000
    };

    enum tagenumSaveFileType {
        TIF_Raw                 = 0,
        TIF_PackBits            = 1,
        TIF_G3                  = 2,
        TIF_G3M                 = 3,
        TIF_G4                  = 4
    };

    enum tagenumScanSetting {
        ScanXResolution         = 0,
        ScanYResolution         = 1,
        ScanPageSize            = 2,
        ScanBrightness          = 3,
        ScanContrast            = 4,
        ScanXPosition           = 5,
        ScanYPosition           = 6,
        ScanImageWidth          = 7,
        ScanImageLength         = 8,
        ScanResUnit             = 9,
        ScanType                = 10,
        ScanAhead               = 11,
        ScanAheadMaxPages       = 12,
        ScanAheadPages          = 13,
        ScanSamplesPerPixel     = 14,
        ScanBitsPerSample       = 15
    };

// forward declarations
    enum tagenumConstants;
    enum tagenumErrors;
    enum tagenumScanSetting;
    enum tagenumSaveFileType;
    enum tagenumChoiceType;
    enum tagenumConstants;
    enum tagenumErrors;
    enum tagenumScanSetting;
    enum tagenumSaveFileType;
    enum tagenumChoiceType;

class SCANXPRLIB_EXPORT IScanXpress : public QAxObject
{
public:
    IScanXpress(IDispatch *subobject = 0, QAxObject *parent = 0)
    : QAxObject((IUnknown*)subobject, parent)
    {
        internalRelease();
    }

    /*
    Property CreateDib

    Causes a Dib to be built while scanning so the hDib property will be valid after each scan.
For more information, see help context 1000 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool CreateDib() const; //Returns the value of CreateDib
    inline void SetCreateDib(bool value); //Sets the value of the CreateDib property

    /*
    Property CreateFile

    Causes a file to be saved using the filename specified by the ScanFileName property.
For more information, see help context 1020 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool CreateFile() const; //Returns the value of CreateFile
    inline void SetCreateFile(bool value); //Sets the value of the CreateFile property

    /*
    Property Debug

    property Debug
For more information, see help context 0 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool Debug() const; //Returns the value of Debug
    inline void SetDebug(bool value); //Sets the value of the Debug property

    /*
    Property Enabled

    For more information, see help context 0 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool Enabled() const; //Returns the value of Enabled
    inline void SetEnabled(bool value); //Sets the value of the Enabled property

    /*
    Property FlipDib

    Flips the Dib that is stored in the hDib property.  This property must be set before a scan takes place.
For more information, see help context 1040 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool FlipDib() const; //Returns the value of FlipDib
    inline void SetFlipDib(bool value); //Sets the value of the FlipDib property

    /*
    Property IHeight

    Returns the height of the current Dib indicated by the hDib property.
For more information, see help context 1080 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int IHeight() const; //Returns the value of IHeight

    /*
    Property IWidth

    Returns the width of the current Dib indicated by the hDib property.
For more information, see help context 1100 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int IWidth() const; //Returns the value of IWidth

    /*
    Property SaveFileType

    The file format to use when saving images. TIFF formats currently.
For more information, see help context 1120 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline ScanXprLib::tagenumSaveFileType SaveFileType() const; //Returns the value of SaveFileType
    inline void SetSaveFileType(ScanXprLib::tagenumSaveFileType value); //Sets the value of the SaveFileType property

    /*
    Property ScanChoiceMax

    Returns highest possible choice for the current scan setting.
For more information, see help context 1180 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanChoiceMax() const; //Returns the value of ScanChoiceMax

    /*
    Property ScanChoiceMin

    Returns lowest possible choice for the current scan setting.
For more information, see help context 1200 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanChoiceMin() const; //Returns the value of ScanChoiceMin

    /*
    Property ScanChoiceType

    Returns type of choice for the current scanner setting.
For more information, see help context 1220 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline ScanXprLib::tagenumChoiceType ScanChoiceType() const; //Returns the value of ScanChoiceType

    /*
    Property ScanErrorCode

    Returns error codes from ISIS driver.
For more information, see help context 1240 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanErrorCode() const; //Returns the value of ScanErrorCode

    /*
    Property ScanErrorString

    Returns error string associated with ScanErrorCode.
For more information, see help context 1260 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanErrorString() const; //Returns the value of ScanErrorString

    /*
    Property ScanFileDir

    The base directory used for the naming schema during batch scans when UseSchema is set to True.
For more information, see help context 1280 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanFileDir() const; //Returns the value of ScanFileDir
    inline void SetScanFileDir(const QString& value); //Sets the value of the ScanFileDir property

    /*
    Property ScanFileName

    The full path and filename a scanned image is saved to.
For more information, see help context 1300 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanFileName() const; //Returns the value of ScanFileName
    inline void SetScanFileName(const QString& value); //Sets the value of the ScanFileName property

    /*
    Property ScanFileRoot

    Root prefix used to generate filenames during a batch scan when UseSchema is set to True.
For more information, see help context 1320 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanFileRoot() const; //Returns the value of ScanFileRoot
    inline void SetScanFileRoot(const QString& value); //Sets the value of the ScanFileRoot property

    /*
    Property ScanFileSchema

    File schema used to generate filenames during batch scanning.
For more information, see help context 1340 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanFileSchema() const; //Returns the value of ScanFileSchema
    inline void SetScanFileSchema(const QString& value); //Sets the value of the ScanFileSchema property

    /*
    Property ScanMultiPage

    Causes the saved TIFF file to be a multi-page TIFF file.
For more information, see help context 1360 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool ScanMultiPage() const; //Returns the value of ScanMultiPage
    inline void SetScanMultiPage(bool value); //Sets the value of the ScanMultiPage property

    /*
    Property ScanName

    The name of the scanner driver.
For more information, see help context 1380 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanName() const; //Returns the value of ScanName
    inline void SetScanName(const QString& value); //Sets the value of the ScanName property

    /*
    Property ScanNumChoices

    Returns the number of available choices if ScanChoiceType is a list for the current scan setting.
For more information, see help context 1420 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanNumChoices() const; //Returns the value of ScanNumChoices

    /*
    Property ScanSetting

    Determines which scanner setting to query/set.
For more information, see help context 1440 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline ScanXprLib::tagenumScanSetting ScanSetting() const; //Returns the value of ScanSetting
    inline void SetScanSetting(ScanXprLib::tagenumScanSetting value); //Sets the value of the ScanSetting property

    /*
    Property ScanSettingAscii

    Returns or sets an ascii string to the current scan setting.
For more information, see help context 1460 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanSettingAscii() const; //Returns the value of ScanSettingAscii
    inline void SetScanSettingAscii(const QString& value); //Sets the value of the ScanSettingAscii property

    /*
    Property ScanSettingLong

    Returns or sets an integer value to the current scan setting.
For more information, see help context 1480 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanSettingLong() const; //Returns the value of ScanSettingLong
    inline void SetScanSettingLong(int value); //Sets the value of the ScanSettingLong property

    /*
    Property ScannerLoaded

    Determines if the scanner driver is loaded.
For more information, see help context 1400 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool ScannerLoaded() const; //Returns the value of ScannerLoaded

    /*
    Property SettingSupported

    Determines if the current scan setting is supported.
For more information, see help context 1500 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool SettingSupported() const; //Returns the value of SettingSupported

    /*
    Property UseCompression

    Enables hardware compression if the scanner supports it.
For more information, see help context 1520 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool UseCompression() const; //Returns the value of UseCompression
    inline void SetUseCompression(bool value); //Sets the value of the UseCompression property

    /*
    Property UseSchema

    Causes a naming schema to be used during batch scanning.
For more information, see help context 1540 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool UseSchema() const; //Returns the value of UseSchema
    inline void SetUseSchema(bool value); //Sets the value of the UseSchema property

    /*
    Property hDib

    After each scan this property will be a handle to a Dib if the CreateDib property is True and the UseCompression property is False.
For more information, see help context 1060 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int hDib() const; //Returns the value of hDib

    /*
    Method About

    Displays the About box
For more information, see help context 0 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void About();

    /*
    Method Cancel

    Interrupts the current scanning.
For more information, see help context 1600 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void Cancel();

    /*
    Method Cancel

    Interrupts the current scanning.
For more information, see help context 1600 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void Cancel(bool bImmediate);

    /*
    Method ClearScanAheadPages

    Clears the scanner’s buffers of any scanned in ahead pages.
For more information, see help context 1620 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ClearScanAheadPages();

    /*
    Method LoadPipe

    Preloads the ISIS drivers used for scanning and saving an image.
For more information, see help context 1640 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void LoadPipe();

    /*
    Method LoadSettings

    Load the settings for the current scanner from an .ini file.
For more information, see help context 1680 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void LoadSettings(const QString& FileName);

    /*
    Method SaveSettings

    Saves the settings for the current scanner to an .ini file.
For more information, see help context 1680 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void SaveSettings(const QString& FileName);

    /*
    Method ScanBatch

    Starts a batch scan process.
For more information, see help context 1700 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void ScanBatch();

    /*
    Method ScanChoiceAscii

    Returns an ascii choice for current scan setting.
For more information, see help context 1140 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanChoiceAscii(int Index);

    /*
    Method ScanChoiceLong

    Returns integer Choice for current scan setting.
For more information, see help context 1160 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanChoiceLong(int Index);

    /*
    Method ScanSingle

    Scans a single page.
For more information, see help context 1720 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void ScanSingle();

    /*
    Method SettingsDialog

    Displays a dialog box that allows the user to change scanner settings.
For more information, see help context 1760 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void SettingsDialog();

    /*
    Method SettingsDialog

    Displays a dialog box that allows the user to change scanner settings.
For more information, see help context 1760 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void SettingsDialog(const QVariant& hWnd);

    /*
    Method SettingsDialog

    Displays a dialog box that allows the user to change scanner settings.
For more information, see help context 1760 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void SettingsDialog(const QVariant& hWnd, const QVariant& dwFlags);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// skipping event interface IScanXprEvents

// Actual coclasses
class SCANXPRLIB_EXPORT ScanXpress : public QAxWidget
{
public:
    ScanXpress(QWidget *parent = 0, Qt::WindowFlags f = 0)
    : QAxWidget(parent, f)
    {
        setControl(QStringLiteral("{a57b5680-36ca-11d2-bd7f-00c0d1572a7b}"));
    }

    ScanXpress(IScanXpress *iface)
    : QAxWidget()
    {
        initializeFrom(iface);
        delete iface;
    }

    /*
    Property CreateDib

    Causes a Dib to be built while scanning so the hDib property will be valid after each scan.
For more information, see help context 1000 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool CreateDib() const; //Returns the value of CreateDib
    inline void SetCreateDib(bool value); //Sets the value of the CreateDib property

    /*
    Property CreateFile

    Causes a file to be saved using the filename specified by the ScanFileName property.
For more information, see help context 1020 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool CreateFile() const; //Returns the value of CreateFile
    inline void SetCreateFile(bool value); //Sets the value of the CreateFile property

    /*
    Property Debug

    property Debug
For more information, see help context 0 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool Debug() const; //Returns the value of Debug
    inline void SetDebug(bool value); //Sets the value of the Debug property

    /*
    Property Enabled

    For more information, see help context 0 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool Enabled() const; //Returns the value of Enabled
    inline void SetEnabled(bool value); //Sets the value of the Enabled property

    /*
    Property FlipDib

    Flips the Dib that is stored in the hDib property.  This property must be set before a scan takes place.
For more information, see help context 1040 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool FlipDib() const; //Returns the value of FlipDib
    inline void SetFlipDib(bool value); //Sets the value of the FlipDib property

    /*
    Property IHeight

    Returns the height of the current Dib indicated by the hDib property.
For more information, see help context 1080 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int IHeight() const; //Returns the value of IHeight

    /*
    Property IWidth

    Returns the width of the current Dib indicated by the hDib property.
For more information, see help context 1100 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int IWidth() const; //Returns the value of IWidth

    /*
    Property SaveFileType

    The file format to use when saving images. TIFF formats currently.
For more information, see help context 1120 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline ScanXprLib::tagenumSaveFileType SaveFileType() const; //Returns the value of SaveFileType
    inline void SetSaveFileType(ScanXprLib::tagenumSaveFileType value); //Sets the value of the SaveFileType property

    /*
    Property ScanChoiceMax

    Returns highest possible choice for the current scan setting.
For more information, see help context 1180 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanChoiceMax() const; //Returns the value of ScanChoiceMax

    /*
    Property ScanChoiceMin

    Returns lowest possible choice for the current scan setting.
For more information, see help context 1200 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanChoiceMin() const; //Returns the value of ScanChoiceMin

    /*
    Property ScanChoiceType

    Returns type of choice for the current scanner setting.
For more information, see help context 1220 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline ScanXprLib::tagenumChoiceType ScanChoiceType() const; //Returns the value of ScanChoiceType

    /*
    Property ScanErrorCode

    Returns error codes from ISIS driver.
For more information, see help context 1240 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanErrorCode() const; //Returns the value of ScanErrorCode

    /*
    Property ScanErrorString

    Returns error string associated with ScanErrorCode.
For more information, see help context 1260 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanErrorString() const; //Returns the value of ScanErrorString

    /*
    Property ScanFileDir

    The base directory used for the naming schema during batch scans when UseSchema is set to True.
For more information, see help context 1280 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanFileDir() const; //Returns the value of ScanFileDir
    inline void SetScanFileDir(const QString& value); //Sets the value of the ScanFileDir property

    /*
    Property ScanFileName

    The full path and filename a scanned image is saved to.
For more information, see help context 1300 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanFileName() const; //Returns the value of ScanFileName
    inline void SetScanFileName(const QString& value); //Sets the value of the ScanFileName property

    /*
    Property ScanFileRoot

    Root prefix used to generate filenames during a batch scan when UseSchema is set to True.
For more information, see help context 1320 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanFileRoot() const; //Returns the value of ScanFileRoot
    inline void SetScanFileRoot(const QString& value); //Sets the value of the ScanFileRoot property

    /*
    Property ScanFileSchema

    File schema used to generate filenames during batch scanning.
For more information, see help context 1340 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanFileSchema() const; //Returns the value of ScanFileSchema
    inline void SetScanFileSchema(const QString& value); //Sets the value of the ScanFileSchema property

    /*
    Property ScanMultiPage

    Causes the saved TIFF file to be a multi-page TIFF file.
For more information, see help context 1360 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool ScanMultiPage() const; //Returns the value of ScanMultiPage
    inline void SetScanMultiPage(bool value); //Sets the value of the ScanMultiPage property

    /*
    Property ScanName

    The name of the scanner driver.
For more information, see help context 1380 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanName() const; //Returns the value of ScanName
    inline void SetScanName(const QString& value); //Sets the value of the ScanName property

    /*
    Property ScanNumChoices

    Returns the number of available choices if ScanChoiceType is a list for the current scan setting.
For more information, see help context 1420 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanNumChoices() const; //Returns the value of ScanNumChoices

    /*
    Property ScanSetting

    Determines which scanner setting to query/set.
For more information, see help context 1440 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline ScanXprLib::tagenumScanSetting ScanSetting() const; //Returns the value of ScanSetting
    inline void SetScanSetting(ScanXprLib::tagenumScanSetting value); //Sets the value of the ScanSetting property

    /*
    Property ScanSettingAscii

    Returns or sets an ascii string to the current scan setting.
For more information, see help context 1460 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanSettingAscii() const; //Returns the value of ScanSettingAscii
    inline void SetScanSettingAscii(const QString& value); //Sets the value of the ScanSettingAscii property

    /*
    Property ScanSettingLong

    Returns or sets an integer value to the current scan setting.
For more information, see help context 1480 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanSettingLong() const; //Returns the value of ScanSettingLong
    inline void SetScanSettingLong(int value); //Sets the value of the ScanSettingLong property

    /*
    Property ScannerLoaded

    Determines if the scanner driver is loaded.
For more information, see help context 1400 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool ScannerLoaded() const; //Returns the value of ScannerLoaded

    /*
    Property SettingSupported

    Determines if the current scan setting is supported.
For more information, see help context 1500 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool SettingSupported() const; //Returns the value of SettingSupported

    /*
    Property UseCompression

    Enables hardware compression if the scanner supports it.
For more information, see help context 1520 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool UseCompression() const; //Returns the value of UseCompression
    inline void SetUseCompression(bool value); //Sets the value of the UseCompression property

    /*
    Property UseSchema

    Causes a naming schema to be used during batch scanning.
For more information, see help context 1540 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline bool UseSchema() const; //Returns the value of UseSchema
    inline void SetUseSchema(bool value); //Sets the value of the UseSchema property

    /*
    Property hDib

    After each scan this property will be a handle to a Dib if the CreateDib property is True and the UseCompression property is False.
For more information, see help context 1060 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int hDib() const; //Returns the value of hDib

    /*
    Method About

    Displays the About box
For more information, see help context 0 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void About();

    /*
    Method Cancel

    Interrupts the current scanning.
For more information, see help context 1600 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void Cancel();

    /*
    Method Cancel

    Interrupts the current scanning.
For more information, see help context 1600 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void Cancel(bool bImmediate);

    /*
    Method ClearScanAheadPages

    Clears the scanner?s buffers of any scanned in ahead pages.
For more information, see help context 1620 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ClearScanAheadPages();

    /*
    Method LoadPipe

    Preloads the ISIS drivers used for scanning and saving an image.
For more information, see help context 1640 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void LoadPipe();

    /*
    Method LoadSettings

    Load the settings for the current scanner from an .ini file.
For more information, see help context 1680 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void LoadSettings(const QString& FileName);

    /*
    Method SaveSettings

    Saves the settings for the current scanner to an .ini file.
For more information, see help context 1680 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void SaveSettings(const QString& FileName);

    /*
    Method ScanBatch

    Starts a batch scan process.
For more information, see help context 1700 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void ScanBatch();

    /*
    Method ScanChoiceAscii

    Returns an ascii choice for current scan setting.
For more information, see help context 1140 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline QString ScanChoiceAscii(int Index);

    /*
    Method ScanChoiceLong

    Returns integer Choice for current scan setting.
For more information, see help context 1160 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline int ScanChoiceLong(int Index);

    /*
    Method ScanSingle

    Scans a single page.
For more information, see help context 1720 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void ScanSingle();

    /*
    Method SettingsDialog

    Displays a dialog box that allows the user to change scanner settings.
For more information, see help context 1760 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void SettingsDialog();

    /*
    Method SettingsDialog

    Displays a dialog box that allows the user to change scanner settings.
For more information, see help context 1760 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void SettingsDialog(const QVariant& hWnd);

    /*
    Method SettingsDialog

    Displays a dialog box that allows the user to change scanner settings.
For more information, see help context 1760 in C:\Windows\SysWow64\ScanXpr.hlp.
    */
    inline void SettingsDialog(const QVariant& hWnd, const QVariant& dwFlags);

// meta object functions
    static const QMetaObject staticMetaObject;
    virtual const QMetaObject *metaObject() const { return &staticMetaObject; }
    virtual void *qt_metacast(const char *);
};

// member function implementation
#ifndef QAX_DUMPCPP_SCANXPRLIB_
inline bool IScanXpress::CreateDib() const
{
    QVariant qax_result = property("CreateDib");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IScanXpress::SetCreateDib(bool value){ setProperty("CreateDib", QVariant(value)); }

inline bool IScanXpress::CreateFile() const
{
    QVariant qax_result = property("CreateFile");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IScanXpress::SetCreateFile(bool value){ setProperty("CreateFile", QVariant(value)); }

inline bool IScanXpress::Debug() const
{
    QVariant qax_result = property("Debug");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IScanXpress::SetDebug(bool value){ setProperty("Debug", QVariant(value)); }

inline bool IScanXpress::Enabled() const
{
    QVariant qax_result = property("Enabled");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IScanXpress::SetEnabled(bool value){ setProperty("Enabled", QVariant(value)); }

inline bool IScanXpress::FlipDib() const
{
    QVariant qax_result = property("FlipDib");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IScanXpress::SetFlipDib(bool value){ setProperty("FlipDib", QVariant(value)); }

inline int IScanXpress::IHeight() const
{
    QVariant qax_result = property("IHeight");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int IScanXpress::IWidth() const
{
    QVariant qax_result = property("IWidth");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline ScanXprLib::tagenumSaveFileType IScanXpress::SaveFileType() const
{
    QVariant qax_result = property("SaveFileType");
    Q_ASSERT(qax_result.isValid());
    return *(ScanXprLib::tagenumSaveFileType*)qax_result.constData();
}
inline void IScanXpress::SetSaveFileType(ScanXprLib::tagenumSaveFileType value){ setProperty("SaveFileType", QVariant(value)); }

inline int IScanXpress::ScanChoiceMax() const
{
    QVariant qax_result = property("ScanChoiceMax");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int IScanXpress::ScanChoiceMin() const
{
    QVariant qax_result = property("ScanChoiceMin");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline ScanXprLib::tagenumChoiceType IScanXpress::ScanChoiceType() const
{
    QVariant qax_result = property("ScanChoiceType");
    Q_ASSERT(qax_result.isValid());
    return *(ScanXprLib::tagenumChoiceType*)qax_result.constData();
}

inline int IScanXpress::ScanErrorCode() const
{
    QVariant qax_result = property("ScanErrorCode");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline QString IScanXpress::ScanErrorString() const
{
    QVariant qax_result = property("ScanErrorString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline QString IScanXpress::ScanFileDir() const
{
    QVariant qax_result = property("ScanFileDir");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IScanXpress::SetScanFileDir(const QString& value){ setProperty("ScanFileDir", QVariant(value)); }

inline QString IScanXpress::ScanFileName() const
{
    QVariant qax_result = property("ScanFileName");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IScanXpress::SetScanFileName(const QString& value){ setProperty("ScanFileName", QVariant(value)); }

inline QString IScanXpress::ScanFileRoot() const
{
    QVariant qax_result = property("ScanFileRoot");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IScanXpress::SetScanFileRoot(const QString& value){ setProperty("ScanFileRoot", QVariant(value)); }

inline QString IScanXpress::ScanFileSchema() const
{
    QVariant qax_result = property("ScanFileSchema");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IScanXpress::SetScanFileSchema(const QString& value){ setProperty("ScanFileSchema", QVariant(value)); }

inline bool IScanXpress::ScanMultiPage() const
{
    QVariant qax_result = property("ScanMultiPage");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IScanXpress::SetScanMultiPage(bool value){ setProperty("ScanMultiPage", QVariant(value)); }

inline QString IScanXpress::ScanName() const
{
    QVariant qax_result = property("ScanName");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IScanXpress::SetScanName(const QString& value){ setProperty("ScanName", QVariant(value)); }

inline int IScanXpress::ScanNumChoices() const
{
    QVariant qax_result = property("ScanNumChoices");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline ScanXprLib::tagenumScanSetting IScanXpress::ScanSetting() const
{
    QVariant qax_result = property("ScanSetting");
    Q_ASSERT(qax_result.isValid());
    return *(ScanXprLib::tagenumScanSetting*)qax_result.constData();
}
inline void IScanXpress::SetScanSetting(ScanXprLib::tagenumScanSetting value){ setProperty("ScanSetting", QVariant(value)); }

inline QString IScanXpress::ScanSettingAscii() const
{
    QVariant qax_result = property("ScanSettingAscii");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void IScanXpress::SetScanSettingAscii(const QString& value){ setProperty("ScanSettingAscii", QVariant(value)); }

inline int IScanXpress::ScanSettingLong() const
{
    QVariant qax_result = property("ScanSettingLong");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void IScanXpress::SetScanSettingLong(int value){ setProperty("ScanSettingLong", QVariant(value)); }

inline bool IScanXpress::ScannerLoaded() const
{
    QVariant qax_result = property("ScannerLoaded");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline bool IScanXpress::SettingSupported() const
{
    QVariant qax_result = property("SettingSupported");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline bool IScanXpress::UseCompression() const
{
    QVariant qax_result = property("UseCompression");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IScanXpress::SetUseCompression(bool value){ setProperty("UseCompression", QVariant(value)); }

inline bool IScanXpress::UseSchema() const
{
    QVariant qax_result = property("UseSchema");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void IScanXpress::SetUseSchema(bool value){ setProperty("UseSchema", QVariant(value)); }

inline int IScanXpress::hDib() const
{
    QVariant qax_result = property("hDib");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline void IScanXpress::About()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 8, _a);
}

inline void IScanXpress::Cancel()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 9, _a);
}

inline void IScanXpress::Cancel(bool bImmediate)
{
    void *_a[] = {0, (void*)&bImmediate};
    qt_metacall(QMetaObject::InvokeMetaMethod, 10, _a);
}

inline int IScanXpress::ClearScanAheadPages()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 11, _a);
    return qax_result;
}

inline void IScanXpress::LoadPipe()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 12, _a);
}

inline void IScanXpress::LoadSettings(const QString& FileName)
{
    void *_a[] = {0, (void*)&FileName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 13, _a);
}

inline void IScanXpress::SaveSettings(const QString& FileName)
{
    void *_a[] = {0, (void*)&FileName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 14, _a);
}

inline void IScanXpress::ScanBatch()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 15, _a);
}

inline QString IScanXpress::ScanChoiceAscii(int Index)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&Index};
    qt_metacall(QMetaObject::InvokeMetaMethod, 16, _a);
    return qax_result;
}

inline int IScanXpress::ScanChoiceLong(int Index)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&Index};
    qt_metacall(QMetaObject::InvokeMetaMethod, 17, _a);
    return qax_result;
}

inline void IScanXpress::ScanSingle()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 18, _a);
}

inline void IScanXpress::SettingsDialog()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 37, _a);
}

inline void IScanXpress::SettingsDialog(const QVariant& hWnd)
{
    void *_a[] = {0, (void*)&hWnd};
    qt_metacall(QMetaObject::InvokeMetaMethod, 38, _a);
}

inline void IScanXpress::SettingsDialog(const QVariant& hWnd, const QVariant& dwFlags)
{
    void *_a[] = {0, (void*)&hWnd, (void*)&dwFlags};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
}


inline bool ScanXpress::CreateDib() const
{
    QVariant qax_result = property("CreateDib");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ScanXpress::SetCreateDib(bool value){ setProperty("CreateDib", QVariant(value)); }

inline bool ScanXpress::CreateFile() const
{
    QVariant qax_result = property("CreateFile");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ScanXpress::SetCreateFile(bool value){ setProperty("CreateFile", QVariant(value)); }

inline bool ScanXpress::Debug() const
{
    QVariant qax_result = property("Debug");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ScanXpress::SetDebug(bool value){ setProperty("Debug", QVariant(value)); }

inline bool ScanXpress::Enabled() const
{
    QVariant qax_result = property("Enabled");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ScanXpress::SetEnabled(bool value){ setProperty("Enabled", QVariant(value)); }

inline bool ScanXpress::FlipDib() const
{
    QVariant qax_result = property("FlipDib");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ScanXpress::SetFlipDib(bool value){ setProperty("FlipDib", QVariant(value)); }

inline int ScanXpress::IHeight() const
{
    QVariant qax_result = property("IHeight");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int ScanXpress::IWidth() const
{
    QVariant qax_result = property("IWidth");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline ScanXprLib::tagenumSaveFileType ScanXpress::SaveFileType() const
{
    QVariant qax_result = property("SaveFileType");
    Q_ASSERT(qax_result.isValid());
    return *(ScanXprLib::tagenumSaveFileType*)qax_result.constData();
}
inline void ScanXpress::SetSaveFileType(ScanXprLib::tagenumSaveFileType value){ setProperty("SaveFileType", QVariant(value)); }

inline int ScanXpress::ScanChoiceMax() const
{
    QVariant qax_result = property("ScanChoiceMax");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline int ScanXpress::ScanChoiceMin() const
{
    QVariant qax_result = property("ScanChoiceMin");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline ScanXprLib::tagenumChoiceType ScanXpress::ScanChoiceType() const
{
    QVariant qax_result = property("ScanChoiceType");
    Q_ASSERT(qax_result.isValid());
    return *(ScanXprLib::tagenumChoiceType*)qax_result.constData();
}

inline int ScanXpress::ScanErrorCode() const
{
    QVariant qax_result = property("ScanErrorCode");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline QString ScanXpress::ScanErrorString() const
{
    QVariant qax_result = property("ScanErrorString");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}

inline QString ScanXpress::ScanFileDir() const
{
    QVariant qax_result = property("ScanFileDir");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ScanXpress::SetScanFileDir(const QString& value){ setProperty("ScanFileDir", QVariant(value)); }

inline QString ScanXpress::ScanFileName() const
{
    QVariant qax_result = property("ScanFileName");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ScanXpress::SetScanFileName(const QString& value){ setProperty("ScanFileName", QVariant(value)); }

inline QString ScanXpress::ScanFileRoot() const
{
    QVariant qax_result = property("ScanFileRoot");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ScanXpress::SetScanFileRoot(const QString& value){ setProperty("ScanFileRoot", QVariant(value)); }

inline QString ScanXpress::ScanFileSchema() const
{
    QVariant qax_result = property("ScanFileSchema");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ScanXpress::SetScanFileSchema(const QString& value){ setProperty("ScanFileSchema", QVariant(value)); }

inline bool ScanXpress::ScanMultiPage() const
{
    QVariant qax_result = property("ScanMultiPage");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ScanXpress::SetScanMultiPage(bool value){ setProperty("ScanMultiPage", QVariant(value)); }

inline QString ScanXpress::ScanName() const
{
    QVariant qax_result = property("ScanName");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ScanXpress::SetScanName(const QString& value){ setProperty("ScanName", QVariant(value)); }

inline int ScanXpress::ScanNumChoices() const
{
    QVariant qax_result = property("ScanNumChoices");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline ScanXprLib::tagenumScanSetting ScanXpress::ScanSetting() const
{
    QVariant qax_result = property("ScanSetting");
    Q_ASSERT(qax_result.isValid());
    return *(ScanXprLib::tagenumScanSetting*)qax_result.constData();
}
inline void ScanXpress::SetScanSetting(ScanXprLib::tagenumScanSetting value){ setProperty("ScanSetting", QVariant(value)); }

inline QString ScanXpress::ScanSettingAscii() const
{
    QVariant qax_result = property("ScanSettingAscii");
    Q_ASSERT(qax_result.isValid());
    return *(QString*)qax_result.constData();
}
inline void ScanXpress::SetScanSettingAscii(const QString& value){ setProperty("ScanSettingAscii", QVariant(value)); }

inline int ScanXpress::ScanSettingLong() const
{
    QVariant qax_result = property("ScanSettingLong");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}
inline void ScanXpress::SetScanSettingLong(int value){ setProperty("ScanSettingLong", QVariant(value)); }

inline bool ScanXpress::ScannerLoaded() const
{
    QVariant qax_result = property("ScannerLoaded");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline bool ScanXpress::SettingSupported() const
{
    QVariant qax_result = property("SettingSupported");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}

inline bool ScanXpress::UseCompression() const
{
    QVariant qax_result = property("UseCompression");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ScanXpress::SetUseCompression(bool value){ setProperty("UseCompression", QVariant(value)); }

inline bool ScanXpress::UseSchema() const
{
    QVariant qax_result = property("UseSchema");
    Q_ASSERT(qax_result.isValid());
    return *(bool*)qax_result.constData();
}
inline void ScanXpress::SetUseSchema(bool value){ setProperty("UseSchema", QVariant(value)); }

inline int ScanXpress::hDib() const
{
    QVariant qax_result = property("hDib");
    Q_ASSERT(qax_result.isValid());
    return *(int*)qax_result.constData();
}

inline void ScanXpress::About()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 39, _a);
}

inline void ScanXpress::Cancel()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 40, _a);
}

inline void ScanXpress::Cancel(bool bImmediate)
{
    void *_a[] = {0, (void*)&bImmediate};
    qt_metacall(QMetaObject::InvokeMetaMethod, 41, _a);
}

inline int ScanXpress::ClearScanAheadPages()
{
    int qax_result;
    void *_a[] = {(void*)&qax_result};
    qt_metacall(QMetaObject::InvokeMetaMethod, 42, _a);
    return qax_result;
}

inline void ScanXpress::LoadPipe()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 43, _a);
}

inline void ScanXpress::LoadSettings(const QString& FileName)
{
    void *_a[] = {0, (void*)&FileName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 44, _a);
}

inline void ScanXpress::SaveSettings(const QString& FileName)
{
    void *_a[] = {0, (void*)&FileName};
    qt_metacall(QMetaObject::InvokeMetaMethod, 45, _a);
}

inline void ScanXpress::ScanBatch()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 46, _a);
}

inline QString ScanXpress::ScanChoiceAscii(int Index)
{
    QString qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&Index};
    qt_metacall(QMetaObject::InvokeMetaMethod, 47, _a);
    return qax_result;
}

inline int ScanXpress::ScanChoiceLong(int Index)
{
    int qax_result;
    void *_a[] = {(void*)&qax_result, (void*)&Index};
    qt_metacall(QMetaObject::InvokeMetaMethod, 48, _a);
    return qax_result;
}

inline void ScanXpress::ScanSingle()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 49, _a);
}

inline void ScanXpress::SettingsDialog()
{
    void *_a[] = {0};
    qt_metacall(QMetaObject::InvokeMetaMethod, 68, _a);
}

inline void ScanXpress::SettingsDialog(const QVariant& hWnd)
{
    void *_a[] = {0, (void*)&hWnd};
    qt_metacall(QMetaObject::InvokeMetaMethod, 69, _a);
}

inline void ScanXpress::SettingsDialog(const QVariant& hWnd, const QVariant& dwFlags)
{
    void *_a[] = {0, (void*)&hWnd, (void*)&dwFlags};
    qt_metacall(QMetaObject::InvokeMetaMethod, 70, _a);
}



#endif

}

QT_BEGIN_NAMESPACE

namespace QtMetaTypePrivate {
template<>
struct QMetaTypeFunctionHelper<ScanXprLib::IScanXpress, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<ScanXprLib::IScanXpress*>(t)->ScanXprLib::IScanXpress::~IScanXpress();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) ScanXprLib::IScanXpress;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const ScanXprLib::IScanXpress*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<ScanXprLib::IScanXpress*>(t); }
#endif // QT_NO_DATASTREAM
};

template<>
struct QMetaTypeFunctionHelper<ScanXprLib::ScanXpress, /* Accepted */ true> {
    static void Destruct(void *t)
    {
        Q_UNUSED(t)
        static_cast<ScanXprLib::ScanXpress*>(t)->ScanXprLib::ScanXpress::~ScanXpress();
    }
    static void *Construct(void *where, const void *t)
    {
        Q_ASSERT(!t);
        Q_UNUSED(t)
        return new (where) ScanXprLib::ScanXpress;
    }
#ifndef QT_NO_DATASTREAM
    static void Save(QDataStream &stream, const void *t) { stream << *static_cast<const ScanXprLib::ScanXpress*>(t); }
    static void Load(QDataStream &stream, void *t) { stream >> *static_cast<ScanXprLib::ScanXpress*>(t); }
#endif // QT_NO_DATASTREAM
};

} // namespace QtMetaTypePrivate
QT_END_NAMESPACE

#endif

